name = "GlobtimDocMonitor"
uuid = "12345678-1234-1234-1234-123456789abc"
version = "2.0.0"

[deps]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Aqua = "0.8"
ArgParse = "1.2"
JSON3 = "1.14"
YAML = "0.4"
julia = "1.10"
